apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  url: http://argocd.localhost
  statusbadge.enabled: "true"
  users.anonymous.enabled: "false"
  passwordPattern: "^.{8,32}$"
  kustomize.buildOptions: --load-restrictor LoadRestrictionsNone
  admin.enabled: "true"
  accounts.reader: login
  accounts.reader.enabled: "false"
  resource.customizations: |
    bitnami.com/SealedSecret:
      health.lua: |
        hs = {}
        hs.status = "Healthy"
        hs.message = "Controller doesn't report resource status"
        return hs
  resource.customizations.ignoreDifferences.admissionregistration.k8s.io_MutatingWebhookConfiguration: |
      jqPathExpressions:
      - '.webhooks[]?.clientConfig.caBundle'
  resource.customizations.ignoreDifferences.admissionregistration.k8s.io_ValidatingWebhookConfiguration: |
      jqPathExpressions:
      - '.webhooks[]?.clientConfig.caBundle'
  dex.config: |
    connectors:
    - type: github
      id: github
      name: GitHub
      config:
        clientID: $argocd-sso-secret:dex.github.clientId
        clientSecret: $argocd-sso-secret:dex.github.clientSecret
        redirectURI: http://argocd.localhost/api/dex/callback
    staticClients:
      - id: argo-workflows-sso
        name: Argo Workflow
        redirectURIs:
          - http://argo.localhost/oauth2/callback
        secretEnv: ARGO_WORKFLOWS_SSO_CLIENT_SECRET

