apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-1"
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: argocd-sso-secret
  namespace: argocd
spec:
  encryptedData:
    dex.github.clientId: AgBQuOLf6MJThI1HzixW1SdnLc9p7F1vjiOi1qRw1FAkIq+gIZf92MIjd6khgI9rQ6OtXno6xI4oMZP5JHp3DI1Dm95w4VkLRaNBnNwLXbb/Dm23GN5fReV4YUo2nxX1p6P5R9feriJnQYqavvYWi9URjbPX46VjF8eJobMlVDZ5LgzPMVir0FYwwSDr9YXwbAdkZ3wxn7T8VwF2imbigu+r87aftj47trO2ydhmFJ6qd8eLwnRaQWbs1cuqP0YrkhHgNyfph2iHOJu3KkFwQjNnVia9zmFPBajq0y5pWUTV0dkrL/63FPPEfhjFV+iyTnmfp1bswkLYotqrZEbftgBeR6bGQOaME4RlhZ4qIh/xFsbady7ybJQ4XdsPVELZl1NqsaM1N1xjMLLbt3R6gpzWfqjB3L7TRV3OitFthprVI4T7NWWEreJgt4NTEQmDxEQJxeEx/L8WRIrr7YAjwHKyhd5zec6OQcb0u/JmkkzDXxCjQlIfJrVlpXgxnLvuhdgRwapOrwhLioSRvpZrRauu8C59piMKQPP4u/eMwZqdI4sGXQ5KztocmYeAgHVFCzzAUX49rkJlLuqiY1fLULRAIi0w2FXF/Q2wmwgvL957fZBfyehRjep+yN2SXFkMBqrK356ME1Ff4MjLg+TUPVut6xr3i/gYLj2XqvITdj/oPavCBJNJcjc3wbbk9W2wYwaEbRBYhKig2bZn2CHwuSx/LQ9rXA==
    dex.github.clientSecret: AgAfPDQhmDffYXP4B8g4qJpa/sBi42AAbnQiJXGWxVtE+blsO4VBJzzslLhJkBMEddcv0Fdi/HbbvH3vBgo8j+z/AG8B2SB2IJIAHfF9tOyGKkG1HKTtZEKy/AdprL9l0nxlXU5rn5QV8H4CdsXsFaOrTGo0sUZWIx4BEVz7gtkurySKDn8mHdUH6wFYtjlwaOgbk84gCorxbpYaAcZpKclEf4rfl1AVvkbevbk29Z/gdt6iQu5t0XTzStFj70yBarWae8V9uva2JGLXos8jc/K9ahJ8tzA/boHrIZYDVYakP8oIlBJ+MDViwJYZxv+prb34NexKRwqF4TSAMqF5Zhb4xXZJqd3rqO144mV97ZrboqHRiKyXMv6P/XQv9fsuvDvxZF4yA/p6DcKy7476gFjuc+gkxInjzj6XlTdUNQOFUWiTWWJL/erG0MBJ3ilTPuJ8lHPLPlK5jb+h7gTy/Wtf16V4EC47E+Z8Dc4OFDcmWlf0zSIXIerYvVPv8smdoDFP8BvqBCYktNOWVniYEJg8ScMvyfflPsOY3ZPM3BwzZe8nF7firgzFTNCy0ke3yjYsZPVtjpNP1hBRJ9JzYkwaF1SbWXP7k3+t4khiHUH67d9EmEQek4+Yp9tck0QOMX2+WtvMduc/vLQ5zRJAHUuAGlWNjFeX1H9OlXU+cgkUPaeythjmz9Ql2o0o7nSz8cpQFnj8GsB09seRL8Of+nTFl57ig98s5HfI/IsA4XGdqpu8BsR9dn2B
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: argocd-sso-secret
      namespace: argocd
    type: Opaque
