apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
data:
  controller.log.format: "json"

  server.insecure: "true"
  server.log.format: "json"
  server.rootpath: "/argocd"

  dexserver.disable.tls: "true"
  dex.server: "http://argocd-dex-server:5556"

  reposerver.log.format: "json"
