apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-1"
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: argocd-sso-secret
  namespace: argocd
spec:
  encryptedData:
    client-id: AgCx+0PNpflycLPrFAdWTh6A/0rEwJMd8qFjyb7uE0PNxbpXaqfic5VljMbYiXi7F6JoTITn3wj5leucKGpch2bsIN39q5QNCv1cO9FmhrbGlDUnMkaGbH4E+ge98mK4H7dSsbhc/QTTeXOBpnHvgV0m4RWDdNT6Q1H0q2Z6fVUreOgG7VN5XbcLHiNZXgrlP8xnT3bAI4M3qG5AHaPRISrAiHfA2GrlpBg2j2NrKdSoWa1+RrAzNmyYBpLV8L8gZ4G8iJDkJ1JIbhKjlmueEqzFZbZ0LqWOnBbYlude5aewd6qdTnZcmWU59/vwzHZU0asg3SB42zaSv0yvsAqC3qngESmr/mn/ADy9YUel335sQACl9THFtlfebvxnhgjv034hNQWpVtbqLu1kKVVWMf5OmoBMx61BBDrKW809YwdxIZ2tUjYBZLtyLyq52K8zDdvbOlSgvowKduRkf6ZSPxyp0Ni7TyhnM8XVj4h4MR7CiPW0jeXA6i7DXCH7BkBsiOPwsj5xrYBN0ioa6frhzmAr5ry/k5MvoVqwn9fkT7Va0gEmg6nf9W5oTQ5Z90pH+FJexgbJU6qK4ODtui9emTb9l4K88j5RrQGLSdsN5quyFqzFbau3QxkxabjlAEm1lAVdaJaRxhyor8Vyr+/lbISDta60+QzKw+VFI4WoRUHZUCp02+SkEGzfn/DNeO+b1R4NnXr41CCT+IkAsrJ6wUuurHZVlA==
    client-secret: AgAIXyjEVZtEnZRqrafjQr9iB1euRcXCohDMpm7imqXpxsWUOP/a5ka8NhtVGDHMeahOh1QOjOXyq6HDhzrAJ89DWsX+GwV6fFNES/GAoCo0+eZDK8PBt1ser/a+pwNYTIMd0yJfXzxyMcn1+mAUFBAcrlV47/TjvVZqoHSWZsniQYWJ1koI/UES347LFMxUhlxKUjV+yaGCbBBNVWA6AZiFDGz70AuOtLsf9YWk6j6fRI5OCsT6l9SmVUixNlq2W4pIbsTrZM17aaWDi0yeVCa65zg4noc7g2pPMmFp22bQTUTiqIeGsC/6xeUsIfZN4GLT8Weib18u71xg1laaPRsRyf8iEeAHM/On5F+/7rWDQofZxX/18mfHVas2hHao/0mzhuxpyn6ET7io0g28U7wHxMEeQuXN92+uXsEKQ3mahq7fZiaO+DD21iBJY5T/kFAHEltJZyBX7ZAa6PB+SIEJO44MnoRdzHY9Dtvdm6z5yDyw7fiYCh1AcJx8T+16IBGXQkmnV9zfQk4lq8G2T/P565spKodqAjlznfBK59FbuZ1t8Vv7GeR3nyvq0dCuEiuvsKyNN/OjJUmsWNPYSiBxvCRO/b9veibwNpy+IlBpvpwk3RBd1QNtulYwc9QYTRz1kKF9g5MhHFSKyarQDYwo5V7N3wcDxl7sjH4lOAkSLGh6pCmKscnM8TpPBrjS4JjWsWvRST96nzYDxwErFci/9joGt3f8i0BqvCxrE3baZ8noqO9ZELyM
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: argocd-sso-secret
      namespace: argocd
    type: Opaque
