apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
data:
  controller.log.format: "json"

  server.insecure: "true"
  server.log.format: "json"
  server.rootpath: "/argocd"

  reposerver.log.format: "json"
