apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-100"
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: argo-workflows-sso
  namespace: argocd
spec:
  encryptedData:
    client-id: AgAW47XWPBMp+hfJFlzIuIJ0BvT3+6PA0ThY5c6DMvribH5Z2iz3kmTPChzjDg122WKSR096LWXsNouOFNmvw/w+QRp/dEz3TpPZvc5F7AeerI0r/eH2/9+IJ5s82X1OychJG5upbMLO4TuHbclH/e9va9whSSz1wEXKG9N6Rgd/WC4mxVkgxacDD28dO8Eg6eLCxWGLkwFOKf/IC2wV3sPLCjgAl71QTBufUR9HrU3FPzzfINses8DCn/eCfQbbu2JVaxNaBjEMqsoHPuOQ1NS/D5MwsfGNSG4fnp6Gf7ct0Hak9Olntr+lfyXNCowKsJg7saGySium4OvxuQEh3TuIpDLpaKx9PBbI0L3fWw7BCqUe0D6capSIfr0GQnqzl/rMU/NWTK4Hw2Tiuz3XoWsFAb2TENiWAX2dG0o4hESlFlMr11EGHvtu8SfeYiqKRGr/Yn4MvMvgJzmwb5xgbX72WhnF0+mWxvCiLE6sWsjJv6ktvgIaNrp3K+O2/o3eFDeCDzfvI3uj8mjouquXxRzsVr0e+u5ImvxU6+WKqjTFlB4DmIDTjJoYauPgBctLWTBT2Tj+5h5A5V1imtv92G2+2F8zdWqrW8qBqtHxbt9Z3VCLtdG2D/Tk4Dx5VhbNTwRAQETs5KeikH9GmgH7bypWGM73EXXh/SyRT8Z4XEDR880fiMkzi6hZi4vKsk2eoKD+lAoIB2c8L+/UzReknrxTVEo=
    client-secret: AgA2MHh0YWhbdpxoTPK/YHWrAn+BpISDv6ws7U+5A6OOY/GgU3/a7Gv6CijApFUEKagkFzR9H9xmOoFz0D9OOw5ynE4PMlSwm10crCRxNN0+GDy3p5hj3twbN8dNQ0JcEXilkooTHe+OETJmIMT2JWuzBMRJ8xjHSBz50Rnh7Byn69n462xMT9NemUcj/Xk5SaYEUoDYVqZI+YmDM2JGQRgsgfHJOAeaRVcmdldX/5/yyd2IvYf+yi//BbKKW0xHC6KorsGQy/IPk0Y012qTU01UsVZ0pUTlt2eyuNxoAO/tfjVfoR2wwtAMVPGJ+4zS8PhcPDSgbZFQoyrFE4IgniaLd1bsiOWIEuJ4tV2u5OR2qHtVeC1r5zNlZCmYClKBfO4b1MDvPdBepMquBQE/zGW9vYZ8xLRry41QQBwtaOs13FwSz2gmUOlUOhy5jWnCByNxPi7HGez66O2NPrdW+U0QqDytBjwXlxwrHS7MMmYMjyAPbJwCFrVImmr7NwRWUMxVOZaFsg7f9NZ80FL08ujs+qChDNbRfEgWqE7fzH53mNQyHjyiDwaoWBzG6BoNs8CKOuqQKfXRgTtGoWUlm6UDKB3cGPxld2olPpxwMEcp+/t+qk+RV14EL9EhJn0zDXjTSl75DLZssg30NPxo1QFF1H4TUPSnNILfg6zetsDfUnkTQNwQIkaWJVnC8t6RkoH/25KAEdhKJ7hpi7B4w01AssXNRSAGNM9dv4Zkerdm3Q==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: argo-workflows-sso
      namespace: argocd
    type: Opaque
