apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-1"
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: argo-workflows-sso
  namespace: argocd
spec:
  encryptedData:
    client-id: AgBy16lmz1MzNJQWlWYbXehW4cdmqEESssJdchKD9a5vTbZvf55OR8go3u4wn+0lrT/evL9jEGktXni7vzGAbuspqvnMxTyU/x2kUqTt9wSz6co9bN0lHGVdCNe3K6UV2oi5HjNCjfwCEQAVJi5R46lBcZUHemfV+fTW7n7IIzcetL1qRuBEagWHDmPwdKq1DokwRa2PhgTtgBTDKHe6Su0XXMWDsSlhGxuSY9zMXOuahm19Fl1mBYOE5GCUwMyi445t7hpEuerJ9bYSGr/QDbCM22Xkk/gXfWphFOMCoy/HBJSAla3X579lguwqV+mySxXUv8W+8Hwuk7yZavQdgsizUtosyb8mHgKfn+J1SgwXEixRHeppgWZjYHI6r9dvwajE74M9h8mM3kksEfr163L9r/dbKAdSMqQeo+eeVsvnfbosQyXHQKt+XyRyj8bMmdDxJEtHV9JhHkF4BvDYiM39gqh40MGMsihJSu47skSENeWahz454GBCYnE3frUFPJ33wYwqzegUYwMlyr2froROti+eE2C7QbJF6GAdJql4tDoy05VESmECPRiLZvMnqy4eXeYAJ94qXslDD8SMx/RgqiGL0vlqzjG2hATWKxBzvwdvmfahuNxb9PwsCy+aNJAtUjvCmih4OXWDoaKbs6t8Xa3oKl2t/G8rhmLuLRmBSiljvS4KlR/skQWmtK+sYGRu2n/MDayUAG5CrBhh
    client-secret: AgB7q77cmLKl8WNVoOUwxERMmh+47jLaFze8UTbNutxmaxtS0ZBFQXnRYFiWSwocNl8mlnwMSHi2zDLjQMPVOYhFLmBXR4TupqOj6ZF57PJL/cZNyHs2Uxg1w5jNJOnomiuAQs4/Vy/GAzjCm9Y8Mm++w7pJCdA0UI3R0St5+B6hPPJCfKIAYJWvO3f26lgk739zEC2lmU+yP1p4TN2NlLEuh9jzjkDBVrPvHJCOk+dEUpqTEc2TvS9GMNdEtqce3eY40jOC2lIeYR57kk8sMcafBeIngrfIvQJmC6J9BxSuleRD/dTyYRbedynRaQH7SZe6E+h5ollIgv2KJACwfBWPTs5Mt6c2rVgvqBI0GIAX/1kVYtQAnO4Djr+CowqrhwhgHWEWijKXIVicN7hGl5ZCCQG3vi1bM2mWjjX5xoHESLTq07RdW0mrnN7SxfM79SYHXcuXhdRyrGYJ9c+rNWUO07znKW4CAdrKSCOgU/R9N/NuPSno1bQH7Xb7vOVADgjQ6L066f9Ne4PTODswv5QKx2bBlzOzDrgqEseKfJ0qD86z5abioON4sLkRBtb68/0mykmW+6w0N3VCKThCwhvfQJJkjF6I10TZWo3YUxLzoQapmND53E570xPUN/sxwDUiRDuQN2E+xfTlEcBtd5+wSsFTkhFWTKrn5GO0UthRrDlkNSHgaywG5BjONaBfrUMVi1g6BUhX6fM8HuXV
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: argo-workflows-sso
      namespace: argocd
    type: Opaque
