apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.5.5/manifests/install.yaml
- root-app.yaml
- project.yaml
- secret.yaml