apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.5.5/manifests/install.yaml
- root-app.yaml
- project.yaml
- argo-workflows-sso.secret.yaml
- argocd-sso.secret.yaml
- routing.yaml

patchesStrategicMerge:
- ./argocd-cm.patch.yaml
- ./argocd-cmd-params-cm.patch.yaml
