apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: k8s-data-ops
spec:
  description: Data Ops Example
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - name: in-cluster
    namespace: '*'
    server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  orphanedResources:
    warn: true
  sourceRepos:
  - https://github.com/mcad7/k8s-data-ops.git
