apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-root
spec:
  project: k8s-data-ops
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: argocd/overlays/prod
    repoURL: 'https://github.com/mcad7/k8s-data-ops.git'
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true